server:
  port: 3000

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  output.ansi.enabled: always

  application:
    name: spring-encrypt